name: Start EC2 Instance

on:
  workflow_dispatch:

jobs:
  start-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Start EC2 instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=GitHubActionsEC2" --query "Reservations[].Instances[].InstanceId" --output text)
          aws ec2 start-instances --instance-ids $INSTANCE_ID
